### ISSUE TITLE
POD NAME structure

### ISSUE THREAD

**Issue by dr0jf** [MARCspec/MARC-Spec#4]
I want to build a Debian package for MARC-Spec. Lintian complains about manpage-has-bad-whatis-entry, which I think is triggered by the structure of the POD NAME element, which is supposed to be "name - description".

**Comment by cKlee** [comment]
Merged your changes. Version 0.1.2 should become available.

**Comment by dr0jf** [comment]
Fixed it, submitted 0.1.2 to Debian. Thanks!
